
export const LOAD_USER = "LOAD_USER";
export const RECEIVED_MESSAGE = "RECEIVED_MESSAGE";
export const CLEAR_USER = "CLEAR_USER";
export const CREATE_CHANNEL = "CREATE_CHANNEL";
export const LOAD_DASHBOARD = "LOAD_DASHBOARD";
export const ACTIVATE_CHANNEL = "ACTIVATE_CHANNEL";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const UPDATE_CHANNELS = "UPDATE_CHANNELS";
